<a href="https://colab.research.google.com/github/QangDuc/deeplearning/blob/main/BTTuan1_DLN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tao array 1 chieu

In [1]:

import numpy as np

# Cách 1
# Tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)

# Chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# Cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [ ]:
c = np.array([(1, 2, 3),
              (4, 5, 6)])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)


f = e.reshape(3, 2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])

print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [ ]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


Thêm dòng dữ liệu với hstack và vstack

In [ ]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


Sinh mảng số nguyên ngẫu nhiên

In [ ]:
import numpy as np
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [46 51 25 55 17]
Random 2-D array
 [[37 62 84 30]
 [41 77 22 24]
 [58 36 55 72]]
Random 3-D array
 [[[84 33  9]
  [15 57 92]
  [27 93 46]
  [20  0 45]]

 [[44 77 24]
  [ 2 27 62]
  [17 57  9]
  [15 88 61]]

 [[56 61 15]
  [16 56  9]
  [64 43 42]
  [73 56 14]]]


Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [ ]:
#sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)
#sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

16
[[10 16  4 10 14]
 [10 14  4 12  4]
 [16 18 18  8 16]]


Thay đổi giá trị của ma trận

In [ ]:
#Tạo ma trận 5 x 5 với số 1
A = np.matrix(np.ones((5, 5)))
print('The matrix\n',A)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Sinh dãy số theo khoảng cho trước
Dùng hàm arange

In [ ]:
#tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1, 20)
print(a)
#tạo 20 số nguyên từ 1 --> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]



Dùng hàm linspace

In [ ]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Index và slice

In [ ]:
#slice
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])
#indexing
print('Second column:', a[:,1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


# Pandas

TÌM HIỂU ĐỐI TƯỢNG SERIES

In [ ]:
import pandas as pd

#Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])
#Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


### Tạo Series từ tệp CSV

Đầu tiên, chúng ta cần một tệp CSV mẫu. Nếu bạn đã có tệp CSV của mình, bạn có thể bỏ qua bước tạo tệp mẫu này.

In [ ]:
# Tạo một tệp CSV mẫu
import pandas as pd

data = {'col1': [10, 20, 30, 40, 50],
        'col2': ['A', 'B', 'C', 'D', 'E']}
df_sample = pd.DataFrame(data)
df_sample.to_csv('sample_data.csv', index=False)

print('Đã tạo tệp sample_data.csv')

Tiếp theo, đọc tệp CSV vào một Pandas DataFrame và sau đó trích xuất một cột để tạo Series.

In [ ]:
# Đọc tệp CSV vào DataFrame
df_from_csv = pd.read_csv('sample_data.csv')

print('DataFrame từ CSV:')
print(df_from_csv)

# Tạo Series từ một cột của DataFrame
series_from_col1 = df_from_csv['col1']

print('\nSeries từ cột "col1":')
print(series_from_col1)
print(type(series_from_col1))

series_from_col2 = df_from_csv['col2']

print('\nSeries từ cột "col2":')
print(series_from_col2)
print(type(series_from_col2))

Nối nhiều DataFrame

In [2]:
import pandas as pd
#Nối 2 DataFrame
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)
#Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))
#Sắp xếp theo cột
print('Sort values in DataFrame\n',df_concat.sort_values('Age'))
#Đổi tên cột
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


Tạo DataFrame mảng 2-chiều có tên cột

In [3]:
import numpy as np
import pandas as pd
dic = {'Name':['John', 'Smith'], 'Age':[30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)
#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) #in 5 dòng đầu tiên

    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0  1.529052 -1.582773 -0.471112 -0.483259
1 -3.183710  0.173386  0.196337 -1.222800
2 -0.335047 -0.630332 -1.198604  0.191443
3  0.193334 -0.435214  0.588399  0.044129
4 -0.223368  0.544421  0.205042  0.807811
