<a href="https://colab.research.google.com/github/QangDuc/deeplearning/blob/main/BTTuan1_DLN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tao array 1 chieu

In [ ]:

import numpy as np

# Cách 1
# Tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)

# Chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# Cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [ ]:
c = np.array([(1, 2, 3),
              (4, 5, 6)])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)


f = e.reshape(3, 2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])

print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [ ]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


Thêm dòng dữ liệu với hstack và vstack

In [ ]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


Sinh mảng số nguyên ngẫu nhiên

In [ ]:
import numpy as np
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [46 51 25 55 17]
Random 2-D array
 [[37 62 84 30]
 [41 77 22 24]
 [58 36 55 72]]
Random 3-D array
 [[[84 33  9]
  [15 57 92]
  [27 93 46]
  [20  0 45]]

 [[44 77 24]
  [ 2 27 62]
  [17 57  9]
  [15 88 61]]

 [[56 61 15]
  [16 56  9]
  [64 43 42]
  [73 56 14]]]


Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [ ]:
#sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)
#sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

16
[[10 16  4 10 14]
 [10 14  4 12  4]
 [16 18 18  8 16]]


Thay đổi giá trị của ma trận

In [ ]:
#Tạo ma trận 5 x 5 với số 1
A = np.matrix(np.ones((5, 5)))
print('The matrix\n',A)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Sinh dãy số theo khoảng cho trước
Dùng hàm arange

In [ ]:
#tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1, 20)
print(a)
#tạo 20 số nguyên từ 1 --> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]



Dùng hàm linspace

In [ ]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Index và slice

In [ ]:
#slice
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])
#indexing
print('Second column:', a[:,1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


# Pandas

TÌM HIỂU ĐỐI TƯỢNG SERIES

In [ ]:
import pandas as pd

#Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])
#Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


### Tạo Series từ tệp CSV

Đầu tiên, chúng ta cần một tệp CSV mẫu. Nếu bạn đã có tệp CSV của mình, bạn có thể bỏ qua bước tạo tệp mẫu này.

In [ ]:
# Tạo một tệp CSV mẫu
import pandas as pd

data = {'col1': [10, 20, 30, 40, 50],
        'col2': ['A', 'B', 'C', 'D', 'E']}
df_sample = pd.DataFrame(data)
df_sample.to_csv('sample_data.csv', index=False)

print('Đã tạo tệp sample_data.csv')

Tiếp theo, đọc tệp CSV vào một Pandas DataFrame và sau đó trích xuất một cột để tạo Series.

In [ ]:
# Đọc tệp CSV vào DataFrame
df_from_csv = pd.read_csv('sample_data.csv')

print('DataFrame từ CSV:')
print(df_from_csv)

# Tạo Series từ một cột của DataFrame
series_from_col1 = df_from_csv['col1']

print('\nSeries từ cột "col1":')
print(series_from_col1)
print(type(series_from_col1))

series_from_col2 = df_from_csv['col2']

print('\nSeries từ cột "col2":')
print(series_from_col2)
print(type(series_from_col2))

Nối nhiều DataFrame

In [ ]:
import pandas as pd
#Nối 2 DataFrame
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)
#Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))
#Sắp xếp theo cột
print('Sort values in DataFrame\n',df_concat.sort_values('Age'))
#Đổi tên cột
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


Tạo DataFrame mảng 2-chiều có tên cột

In [ ]:
import numpy as np
import pandas as pd
dic = {'Name':['John', 'Smith'], 'Age':[30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)
#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) #in 5 dòng đầu tiên

    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0  1.529052 -1.582773 -0.471112 -0.483259
1 -3.183710  0.173386  0.196337 -1.222800
2 -0.335047 -0.630332 -1.198604  0.191443
3  0.193334 -0.435214  0.588399  0.044129
4 -0.223368  0.544421  0.205042  0.807811


#TENSORFLOW

Tensor 0-chiều

In [1]:
import tensorflow as tf
# This will be an int32 tensor by default;
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


tạo một tensor scalar với kiểu dữ liệu là int16, float32 và string

In [2]:
# This will be an int32 tensor by default;
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
print(r1)
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


Tensor 1-chiều

In [3]:
# We make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


Tensor 2-chiều (ma trận)

In [4]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


Tensor n-chiều (nhiều trục)

In [5]:
rank_3_tensor = tf.constant([
                             [[0, 1, 2, 3, 4],
                              [5, 6, 7, 8, 9]],
                             [[10, 11, 12, 13, 14],
                              [15, 16, 17, 18, 19]],
                             [[20, 21, 22, 23, 24],
                              [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


Thuộc tính của tensor:
  Label (name)
  Dimension (shape)
  Data type (dtype

In [6]:
rank_3_tensor = tf.constant([
                             [[0, 1, 2, 3, 4],
                              [5, 6, 7, 8, 9]],
                             [[10, 11, 12, 13, 14],
                              [15, 16, 17, 18, 19]],
                             [[20, 21, 22, 23, 24],
                              [25, 26, 27, 28, 29]],])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:',rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


Tạo tensor tự động gán giá trị 0 ban đầu

In [8]:
t_zero = tf.zeros(10)
print(t_zero)
t_2_zero = tf.zeros([3, 3])
print(t_2_zero)
t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


Tạo tensor tự động gán giá trị 1 ban đầu

In [9]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3,3])
print(t_2_one)

t_3_one = tf.ones([3,3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


Tạo tensor tự động với giá trị bất kỳ

In [10]:
t_1 = tf.fill(3, 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


Tạo tensor 1-chiều với hàm linspace

In [11]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


Tạo tensor 1-chiều với hàm range

In [12]:
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [13]:
range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


Tạo tensor với giá trị ngẫu nhiên

tạo tensor ngẫu nhiên với hàm random.normal

In [14]:
range_tensor = tf.random.normal([5])
print(range_tensor)

range_tensor = tf.random.normal([3, 3])
print(range_tensor)

tf.Tensor([-0.5538208   2.3708994  -0.7061729   0.4211936   0.44931757], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.36678094 -1.3187946  -0.62384343]
 [ 1.0183709  -0.6768885   1.2966763 ]
 [-0.67477953 -0.14396714 -0.08246168]], shape=(3, 3), dtype=float32)


tạo tensor ngẫu nhiên với hàm random.truncated_normal

In [15]:
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

tf.Tensor([-1.1402788  -0.19548877 -0.24430117  0.01858707  0.45019993], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.41892055  1.5304949 ]
 [-0.07957768  0.6917823 ]
 [-0.7287289   0.6164984 ]], shape=(3, 2), dtype=float32)


Chuyển đổi kiểu dữ liệu

In [16]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)
t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '---', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


Các phép toán trong tensorflow

Tính căn bậc 2 của một tensor scalar

In [17]:
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)


Cộng 2 tensor

In [18]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.add(a, b)
d = a + b
print(c)
print(d)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


Nhân 2 tensor

In [19]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.multiply(a, b)
d = a * b
print(c)
print(d)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [20]:
a = tf.constant([6. , 6. , 6.])
b = tf.constant([4. , 4. , 4.])
c = tf.constant([3. , 3. , 3.])
d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print(i)
print(l)

tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


Các phép toán so sánh trong tensorflow

In [21]:
x = tf.constant([5, 4, 6, 7])
y = tf.constant([5, 2, 8, 9])

z1 = tf.equal(x, y)
z2 = tf.not_equal(x, y)
z3 = tf.less(x, y)
z4 = tf.less_equal(x, y)
z5 = tf.greater(x, y)
z6 = tf.greater_equal(x, y)

print(z1)
print(z3)
print(z5)

tf.Tensor([ True False False False], shape=(4,), dtype=bool)
tf.Tensor([False False  True  True], shape=(4,), dtype=bool)
tf.Tensor([False  True False False], shape=(4,), dtype=bool)


Các phép toán trên vector và ma trận

In [22]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)

print(t1)
print(t2)
print(t3)
print(t4)

cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


Biến trong tensorflow

In [23]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

diem = tf.Variable([5, 9])
print(diem)
print('Shape', diem.shape)
print('Dtype', diem.dtype)
print('numpy:', diem.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape (2,)
Dtype <dtype: 'int32'>
numpy: [5 9]


In [24]:
#Gán lại giá trị mới bằng hàm assign
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

diem = tf.Variable([5, 9])
print(diem)

diem.assign([8, 10])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>


In [25]:
#Cộng thêm vào giá trị hiện tại bằng hàm assign_add
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

diem = tf.Variable([5, 9])
print(diem)

diem.assign([8, 10])
diem.assign_add([1, 1])

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 9, 11], dtype=int32)>

Modules, Layers và Models

In [29]:
class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]), name='w')
        self.b = tf.Variable(tf.zeros([out_features]), name='b')

    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

        self.dense_1 = Dense(in_features=3, out_features=3)
        self.dense_2 = Dense(in_features=3, out_features=2)

    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)

# # You have made a model!
my_model = SequentialModule(name="the_model")

# # Call it, with random results
print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

Model results: tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
